org.gradle.jvmargs=-Xmx3G

# Mod Properties
mod_version=1.2.0

# Build Info
minecraft_version=26.1
fabric_loader_version=0.18.4
forge_version=62.0.0
forge_eventbus_version=7.0-beta.7
neoforge_version=26.1.0.19-beta
neoforge_fml_version=11.0.5

# Dependencies
yet_another_config_lib_version=3.9.0+26.1
mod_menu_version=18.0.0-alpha.8
