name: Build Mica

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup git config
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Action"

      - name : Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mica-artifacts
          path: |
            fabric/build/libs/mica-**.jar
            !fabric/build/libs/mica-**-dev-shadow.jar
            !fabric/build/libs/mica-**-sources.jar
            forge/build/libs/mica-**.jar
            !forge/build/libs/mica-**-dev-shadow.jar
            !forge/build/libs/mica-**-sources.jar
            neoforge/build/libs/mica-**.jar
            !neoforge/build/libs/mica-**-dev-shadow.jar
            !neoforge/build/libs/mica-**-sources.jar
